"""Pydantic models shared across stages. Stable schema is important since the Sheet is the source of truth."""
from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import BaseModel, Field


class ParsedJob(BaseModel):
    """Output of parse_job.py."""

    company_name: str
    company_domain: Optional[str] = None
    role_title: str
    location: Optional[str] = None
    jd_body: str
    posted_date: Optional[str] = None
    recruiter_name: Optional[str] = None
    job_url: str
    source_site: Optional[str] = None  # lever | greenhouse | workday | linkedin | indeed | other


class ParsedPost(BaseModel):
    """Output of parse_post.py — what we recover from a LinkedIn post URL via httpx + OG/JSON-LD."""

    author_name: str
    profile_slug: str
    post_url: str
    # Snippet from og:description and/or JSON-LD articleBody. None when LinkedIn
    # locked the page down enough that we got nothing usable. Drafter degrades to
    # an honest credentialed pitch when None.
    post_snippet: Optional[str] = None
    fetched_at: datetime


class Contact(BaseModel):
    """One target contact. Output of clay_lookup or post-author resolution."""

    name: str
    title: str
    company: str
    linkedin_url: Optional[str] = None
    email: Optional[str] = None  # None => email_pending, no Gmail draft
    role_priority: int = Field(default=3, ge=1, le=4)  # 1 = post author, 2-4 = JD contacts
    source: Literal["post_author", "clay_search"] = "clay_search"


class EmailDraft(BaseModel):
    subject: str
    body: str
    word_count: int


class LinkedInDraft(BaseModel):
    """Manual-send LinkedIn surfaces. You copy these from the Sheet into LinkedIn directly.

    No auto-send — Step 7's loop will not push these to LinkedIn for v1.
    """
    connection_note: str  # < 300 chars; sent with the connection request
    dm: str               # < 500 chars; sent AFTER they accept the connection


class StagedRow(BaseModel):
    """Mirrors the columns appended to the Google Sheet."""

    date_added: datetime
    company: str
    role: str
    job_url: str
    contact_name: str
    title: str
    email: Optional[str] = None
    linkedin: Optional[str] = None
    status: str = "Drafted"
    last_action_date: Optional[datetime] = None
    next_action: str = "Send Email 1"
    next_action_date: Optional[datetime] = None
    email_1_sent: Optional[datetime] = None
    email_2_sent: Optional[datetime] = None
    email_3_sent: Optional[datetime] = None
    replied: bool = False
    reply_date: Optional[datetime] = None
    notes: str = ""
    gmail_draft_id: Optional[str] = None
    # LinkedIn surfaces — populated by drafter for manual copy-paste. You send from LinkedIn directly.
    linkedin_connection_note: Optional[str] = None
    linkedin_dm: Optional[str] = None
    # InMail kept for schema stability; not generated by current drafter.
    linkedin_inmail_subject: Optional[str] = None
    linkedin_inmail_body: Optional[str] = None
    # --- Step 7 tracking (manual-send detection + follow-ups) ---
    gmail_message_id: Optional[str] = None
    gmail_subject: Optional[str] = None
    gmail_thread_id: Optional[str] = None
    last_gmail_message_id: Optional[str] = None
    followup_draft_id: Optional[str] = None
    reply_draft_id: Optional[str] = None       # populated in Phase 2
    step7_error: str = ""
    followup_sent: bool = False
    followup_date: Optional[datetime] = None
