"""Test fixtures shared across the suite.

Production code reads Profile/voice_config.yaml and the Profile/*.md pack at
runtime. Neither exists in this repo by design — they're per-user files
generated by `apply init`. Tests get autouse monkeypatches that supply stubs.

We patch at the import site (src.lib.draft_outreach.load_profile, etc.) rather
than the source module, because `from X import Y` binds Y as a separate name
in the importing module's namespace.
"""
from __future__ import annotations

import pytest

from src.lib import profile as profile_module
from src.lib import voice_rules as voice_rules_module
from src.lib.voice_rules import VoiceConfig


_STUB_PROFILE_PACK = profile_module.ProfilePack(
    resume="# Stub Resume\nFictional persona for tests. Built things, shipped things.",
    voice="# Stub Voice\n- Short. 50-110 words.\n- Sign off with the configured signature.",
    proof_points="- Built a self-serve funnel from scratch.\n- Grew signups from zero to 10k in a year.",
    past_drafts="# Past drafts (stub)\n\n*Email 1*\nHi NAME,\n\nApplied today. Built X. Would love 15 min.\n\nAlex",
    narrative="# Narrative (stub)\nBuilder who likes building zero-to-one teams.",
)


_DEFAULT_TEST_CONFIG = VoiceConfig(
    signature="Alex",
    banned_phrases=(
        "is exactly the kind of work",
        "the kind of work I've been",
        "I think that",
        "maps well",
        "want to reach out",
        "Sounds like what",
        "where the company is heading",
        "builder instinct",
        "Quick context",
        "Quick note",
        "one of three I'm serious about",
        "if you have a minute",
        "no worries if not",
        "let me know your availability",
    ),
)


def _stub_profile_fn():
    return _STUB_PROFILE_PACK


def _stub_voice_config_fn(_profile_dir=None):
    return _DEFAULT_TEST_CONFIG


@pytest.fixture(autouse=True)
def _stub_profile(monkeypatch):
    """Stub load_profile everywhere it's imported, plus the source module."""
    profile_module.load_profile.cache_clear()
    monkeypatch.setattr(profile_module, "load_profile", _stub_profile_fn)
    # Patch at every import site so `from src.lib.profile import load_profile` gets the stub too.
    import src.lib.draft_outreach as draft_outreach_module
    monkeypatch.setattr(draft_outreach_module, "load_profile", _stub_profile_fn)


@pytest.fixture(autouse=True)
def _stub_voice_config(monkeypatch):
    """Stub load_voice_config everywhere it's imported, plus the source module."""
    voice_rules_module.load_voice_config.cache_clear()
    monkeypatch.setattr(voice_rules_module, "load_voice_config", _stub_voice_config_fn)
    import src.lib.draft_outreach as draft_outreach_module
    monkeypatch.setattr(draft_outreach_module, "load_voice_config", _stub_voice_config_fn)


@pytest.fixture
def voice_config() -> VoiceConfig:
    """Explicit VoiceConfig for tests that want to pass it directly."""
    return VoiceConfig(signature="Alex")
